carmaa786/carmaa786.github.io

contactus/index.html, js/contactus.js
=> Contact Us Form Updated

components/footer.html, components/footer2.html, css/footer.css
=>  Footer UI Updated

.github/pull_request_template.md, .gitignore
Description:
Added .gitignore file and .github folder to improve project structure and maintainability.
Related Issue : N/A
QA Instructions:
Ensure .gitignore is correctly filtering unnecessary files.
Verify .github folder is properly set up for project workflows.
=> add gitignore and PR template

blogs/index.html, blogs/top-rated-doorstep-car-cleaning-car-wash-service-in-noida/index.html
Resolved the issue related to blog url.
Closes #
For more info, check out the Forem Accessibility Docs.
We encourage you to keep the code coverage percentage at 80% and above.
=> fixed the issue related to blog url

blogs/doorstep-car-cleaning-service-noida/index.html
Closes #
For more info, check out the Forem Accessibility Docs.
We encourage you to keep the code coverage percentage at 80% and above.
=> url change

index.html
This PR is experimental and explains how to check auth via Google captch
Closes #
=> Rnd for captcha

blogs/car-maintenance-doorstep-services/index.html, blogs/doorstep-car-cleaning-service-noida/index.html, blogs/how-to-wash-your-car-without-a-hose/index.html, blogs/the-ultimate-doorstep-car-wash-service-provider-in-dehradun/index.html, blogs/top-tips-for-exterior-and-interior-car-cleaning/index.html, blogs/ultimate-guide-to-car-cleaning-2025/index.html, blogs/ultimate-guide-to-doorstep-car-wash/index.html, blogs/why-carmaa-carcare-is-perfect-for-car-cleaning-services-at-home/index.html, car-body-polish-and-car-waxing-service/index.html, car-deep-cleaning-services/index.html, car-detailing-services/index.html, car-dry-cleaning-service/index.html, ceramic-coating-service/index.html, contactus/index.html, doorstep-car-washing-service-in-dehradun/index.html, doorstep-car-washing-service-in-noida/index.html, doorstep-car-washing-service-in-uttarakhand/index.html, exterior-car-cleaning-washing/index.html, franchise/index.html, full-car-detailing-service/index.html, full-car-wash-service/index.html, glass-and-surface-coating-services/index.html, interior-car-cleaning-service/index.html, js/contactus.js, js/franchise.js, paint-protection-and-coating-services/index.html, pricing/index.html
Added captcha  code in all CTA . 
Closes #
=> added capta in all cta

blogs/car-maintenance-doorstep-services/index.html, blogs/doorstep-car-cleaning-service-noida/index.html, blogs/how-to-wash-your-car-without-a-hose/index.html, blogs/the-ultimate-doorstep-car-wash-service-provider-in-dehradun/index.html, blogs/top-tips-for-exterior-and-interior-car-cleaning/index.html, blogs/ultimate-guide-to-car-cleaning-2025/index.html, blogs/ultimate-guide-to-doorstep-car-wash/index.html, blogs/why-carmaa-carcare-is-perfect-for-car-cleaning-services-at-home/index.html
Added suggestion part in blogs
Closes #
=> Added suggestion blogs

index.html
The typed content is not showing on Carmaa website, the issue has been resolved.
Closes #
=> typed content issue resolve

Doorstep-car-decoration-service-in-dehradun/index.html, about/index.html, components/navbar.html, doorstep-car-washing-service-in-dehradun/index.html, doorstep-car-washing-service-in-noida/index.html, doorstep-car-washing-service-in-uttarakhand/index.html, index.html, pricing/index.html
=> added carmaa app link in download buttons with some minor changes

sitemap.xml
=> update sitemap file

css/contactus.css, franchise/index.html, js/franchise.js
=> added partner with us

blogs/doorstep-car-decor-in-dehradun/index.html
Canonical url updated
Closes #
=> added correct canonical url

about/index.html
Logo flashing issue resolve, added preload css in it .
Closes #
=> added preload css for logo flashing issue

blogs/dry-cleaning-services-at-your-doorstep/index.html, blogs/index.html
Update new blog of dry cleaning service.
Closes #
=> updated new blog

app/android/index.html
=> added android redirect

css/updatedHomePage.css, index.html
ui enhancement of carousal 
Closes #
=> carousal-enhancement

css/homepage.css, index.html
changes in videos of home page with changes in css 
Closes #
=> added video in phone size

Doorstep-car-decoration-service-in-dehradun/index.html, about/index.html, components/footer3.html, doorstep-car-washing-service-in-dehradun/index.html, index.html
Added white google play button
Closes #
=> added google play store image

terms-conditions/index.html
=> spelling correction

best-car-mechanics-in-dehradun/index.html, css/city.css, css/homepage.css, index.html
Bug fixed in car mechanic service. 
i) Added car mechanic service in home page search section.
ii) bug resolved in css of car mechanic service.
Closes #
=> new service bug fixed

best-car-mechanics-in-dehradun/index.html, index.html
Bug resolved in new service . 
Closes #
=> resolved bugs of car mechanic service

app/ios/index.html
=> ios feature

app/index.html
=> added dynamic url

Doorstep-car-decoration-service-in-dehradun/index.html, about/index.html, best-car-mechanics-in-dehradun/index.html, css/common.css, css/homepage.css, css/modal.css, css/updatedHomePage.css, doorstep-car-washing-service-in-dehradun/index.html, doorstep-car-washing-service-in-noida/index.html, doorstep-car-washing-service-in-uttarakhand/index.html, index.html, pricing/index.html
Added google play button and ios play button in website .
Closes #
- [] No new errors or warnings
=> added google play button

index.html
Updated Home page FAQs 
Closes #
=> added new FAQs in home page

css/homepage.css, index.html
Added animation and transitions in home page . 
Closes #
=> added animations

Doorstep-car-decoration-service-in-dehradun/index.html, about/index.html, best-car-mechanics-in-dehradun/index.html, blogs/blogs.css, blogs/dry-cleaning-services-at-your-doorstep/index.html, blogs/index.html, car-detailing-services/index.html, components/navbar.html, contactus/index.html, css/aboutus.css, css/city.css, css/common.css, css/contactus.css, css/fanchise.css, css/footer.css, css/globalCss/navbarGlobal.css, css/homeNavbar.css, css/homepage.css, css/pricing.css, css/service.css, css/timeline.css, doorstep-car-washing-service-in-roorkee/index.html, franchise/index.html, index.html, interior-car-cleaning-service/index.html, pricing/index.html
Added new font Lexend with some changes in css. 
Closes #
=> added font-family with some changes

contactus/index.html, index.html
Updated GMB local search schema
Closes #
=> added schema changes

doorstep-car-washing-service-in-dehradun/index.html, doorstep-car-washing-service-in-noida/index.html
Added FAQs and Review sections in dehradun and noida pages
Closes #
=> added FAQs and reviews in noida and dehradun pages

components/footer3.html, components/navbar.html, doorstep-car-washing-service-in-Rishikesh/index.html
Added new page for location (RISHIKESH) 
Closes #
=> added rishikesh page in website

components/footer3.html, components/navbar.html, doorstep-car-washing-service-in-delhi/index.html
=> added delhi page

open-app/index.html
- [ ✅] Adding a new feature
Closes #
- [✅] My code follows the project rules
- [✅] I checked my own code
- [✅] No new errors or warnings
- [✅] Local Tested end-to-end
- [✅] Module Developed Tested
- [✅ ] Ticket Number
- [✅] Updated tests or documentation if needed
=> App opener link

open-app/index.html
=> App opener link changes

open-app/index.html
=> App opener link issue resolved

open-app/index.html
=> App open link fallback added

components/footer3.html, components/navbar.html, doorstep-car-washing-service-in-meerut/index.html
=> added meerut page

components/footer3.html, components/navbar.html, css/globalCss/navbarGlobal.css, doorstep-car-washing-service-in-Haldwani/index.html
=> added haldwani page

index.html
=> added term changes
